// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package billets.proxies;

public class Billet
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject billetMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Billets.Billet";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Ref("Ref"),
		Nom("Nom"),
		PrixHT("PrixHT"),
		TTC("TTC"),
		IdProduct("IdProduct"),
		Affiche("Affiche"),
		NombreBillet("NombreBillet");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Billet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Billets.Billet"));
	}

	protected Billet(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject billetMendixObject)
	{
		if (billetMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Billets.Billet", billetMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Billets.Billet");

		this.billetMendixObject = billetMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Billet.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static billets.proxies.Billet initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return billets.proxies.Billet.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static billets.proxies.Billet initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new billets.proxies.Billet(context, mendixObject);
	}

	public static billets.proxies.Billet load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return billets.proxies.Billet.initialize(context, mendixObject);
	}

	public static java.util.List<billets.proxies.Billet> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<billets.proxies.Billet> result = new java.util.ArrayList<billets.proxies.Billet>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Billets.Billet" + xpathConstraint))
			result.add(billets.proxies.Billet.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Ref
	 */
	public final java.lang.Integer getRef()
	{
		return getRef(getContext());
	}

	/**
	 * @param context
	 * @return value of Ref
	 */
	public final java.lang.Integer getRef(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Ref.toString());
	}

	/**
	 * Set value of Ref
	 * @param ref
	 */
	public final void setRef(java.lang.Integer ref)
	{
		setRef(getContext(), ref);
	}

	/**
	 * Set value of Ref
	 * @param context
	 * @param ref
	 */
	public final void setRef(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer ref)
	{
		getMendixObject().setValue(context, MemberNames.Ref.toString(), ref);
	}

	/**
	 * @return value of Nom
	 */
	public final java.lang.String getNom()
	{
		return getNom(getContext());
	}

	/**
	 * @param context
	 * @return value of Nom
	 */
	public final java.lang.String getNom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nom.toString());
	}

	/**
	 * Set value of Nom
	 * @param nom
	 */
	public final void setNom(java.lang.String nom)
	{
		setNom(getContext(), nom);
	}

	/**
	 * Set value of Nom
	 * @param context
	 * @param nom
	 */
	public final void setNom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nom)
	{
		getMendixObject().setValue(context, MemberNames.Nom.toString(), nom);
	}

	/**
	 * @return value of PrixHT
	 */
	public final java.math.BigDecimal getPrixHT()
	{
		return getPrixHT(getContext());
	}

	/**
	 * @param context
	 * @return value of PrixHT
	 */
	public final java.math.BigDecimal getPrixHT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.PrixHT.toString());
	}

	/**
	 * Set value of PrixHT
	 * @param prixht
	 */
	public final void setPrixHT(java.math.BigDecimal prixht)
	{
		setPrixHT(getContext(), prixht);
	}

	/**
	 * Set value of PrixHT
	 * @param context
	 * @param prixht
	 */
	public final void setPrixHT(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal prixht)
	{
		getMendixObject().setValue(context, MemberNames.PrixHT.toString(), prixht);
	}

	/**
	 * @return value of TTC
	 */
	public final java.math.BigDecimal getTTC()
	{
		return getTTC(getContext());
	}

	/**
	 * @param context
	 * @return value of TTC
	 */
	public final java.math.BigDecimal getTTC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TTC.toString());
	}

	/**
	 * Set value of TTC
	 * @param ttc
	 */
	public final void setTTC(java.math.BigDecimal ttc)
	{
		setTTC(getContext(), ttc);
	}

	/**
	 * Set value of TTC
	 * @param context
	 * @param ttc
	 */
	public final void setTTC(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ttc)
	{
		getMendixObject().setValue(context, MemberNames.TTC.toString(), ttc);
	}

	/**
	 * @return value of IdProduct
	 */
	public final java.lang.Long getIdProduct()
	{
		return getIdProduct(getContext());
	}

	/**
	 * @param context
	 * @return value of IdProduct
	 */
	public final java.lang.Long getIdProduct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.IdProduct.toString());
	}

	/**
	 * Set value of IdProduct
	 * @param idproduct
	 */
	public final void setIdProduct(java.lang.Long idproduct)
	{
		setIdProduct(getContext(), idproduct);
	}

	/**
	 * Set value of IdProduct
	 * @param context
	 * @param idproduct
	 */
	public final void setIdProduct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long idproduct)
	{
		getMendixObject().setValue(context, MemberNames.IdProduct.toString(), idproduct);
	}

	/**
	 * @return value of Affiche
	 */
	public final java.lang.String getAffiche()
	{
		return getAffiche(getContext());
	}

	/**
	 * @param context
	 * @return value of Affiche
	 */
	public final java.lang.String getAffiche(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Affiche.toString());
	}

	/**
	 * Set value of Affiche
	 * @param affiche
	 */
	public final void setAffiche(java.lang.String affiche)
	{
		setAffiche(getContext(), affiche);
	}

	/**
	 * Set value of Affiche
	 * @param context
	 * @param affiche
	 */
	public final void setAffiche(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String affiche)
	{
		getMendixObject().setValue(context, MemberNames.Affiche.toString(), affiche);
	}

	/**
	 * @return value of NombreBillet
	 */
	public final java.lang.Integer getNombreBillet()
	{
		return getNombreBillet(getContext());
	}

	/**
	 * @param context
	 * @return value of NombreBillet
	 */
	public final java.lang.Integer getNombreBillet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NombreBillet.toString());
	}

	/**
	 * Set value of NombreBillet
	 * @param nombrebillet
	 */
	public final void setNombreBillet(java.lang.Integer nombrebillet)
	{
		setNombreBillet(getContext(), nombrebillet);
	}

	/**
	 * Set value of NombreBillet
	 * @param context
	 * @param nombrebillet
	 */
	public final void setNombreBillet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nombrebillet)
	{
		getMendixObject().setValue(context, MemberNames.NombreBillet.toString(), nombrebillet);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return billetMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final billets.proxies.Billet that = (billets.proxies.Billet) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Billets.Billet";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
