// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package billets.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Billets module
	public static void ajouterProduitDansPanier(IContext context, billets.proxies.Billet _billet, billets.proxies.Panier _panier)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Billet", _billet == null ? null : _billet.getMendixObject());
		params.put("Panier", _panier == null ? null : _panier.getMendixObject());
		Core.microflowCall("Billets.AjouterProduitDansPanier").withParams(params).execute(context);
	}
	public static billets.proxies.Panier ajoutPanier(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Billets.AjoutPanier").withParams(params).execute(context);
		return result == null ? null : billets.proxies.Panier.initialize(context, result);
	}
	public static java.math.BigDecimal calculTVA(IContext context, billets.proxies.Billet _entity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Entity", _entity == null ? null : _entity.getMendixObject());
		return (java.math.BigDecimal) Core.microflowCall("Billets.CalculTVA").withParams(params).execute(context);
	}
	public static void crerUneComande(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Billets.CrerUneComande").withParams(params).execute(context);
	}
}